CREATE TABLE sales (
  id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  amount INT(10) NOT NULL,
  buyer VARCHAR(255) NOT NULL,
  receipt_id VARCHAR(20) NOT NULL,
  items VARCHAR(255) NOT NULL,
  buyer_email VARCHAR(50) NOT NULL,
  buyer_ip VARCHAR(20),
  note TEXT NOT NULL,
  city VARCHAR(20) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  hash_key VARCHAR(255),
  entry_at DATE,
  entry_by INT(10) NOT NULL
);